config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'collections#index'
  resources :collections do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:show, :create, :destroy]
  end
  resources :users, only: :show do
    resources :donations, only: [:new, :create, :show]
    resource :relationships, only: [:show, :create, :destroy]
    get :favorites, on: :collection
  end
  resource :profile, only: [:show, :edit, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '自然' },
    { id: 3, name: '絵画' },
    { id: 4, name: 'インテリア' },
    { id: 5, name: '小物' },
    { id: 6, name: '本' },
    { id: 7, name: '音楽' },
    { id: 8, name: 'ゲーム' },
    { id: 9, name: 'おもちゃ' },
    { id: 10, name: 'グッズ' },
    { id: 11, name: 'プラモデル' },
    { id: 12, name: 'フィギュア' },
    { id: 13, name: 'ハンドメイド' },
    { id: 14, name: 'その他' }
  ]


  include ActiveHash::Associations
  has_many :collections


  end

app/models/collection.rb
class Collection < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :favorites, dependent: :destroy 
  has_many_attached :images

  with_options presence: true do
    validates :title
    validates :point
    validates :category_id,           numericality: { other_than: 1 , message: "を選択してください"}
  end
  validates :images, presence: true 
  validates :images, length: { minimum: 1, maximum: 5, message: "は1枚以上5枚以下にしてください" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :collection

  validates :text, presence: true
end

app/models/donation.rb
class Donation < ApplicationRecord
  attr_accessor :token
  validates :price, presence: true
  validates :text,  presence: true
  validates :token, presence: true

  belongs_to :user
  belongs_to :donationd, class_name: "User", foreign_key: "donationd_id"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user   
  belongs_to :collection   

  validates_uniqueness_of :collection_id, scope: :user_id
  
  def self.count_by_collection(collection_id)
    where(collection_id: collection_id).count
  end

end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1,  type: '---' },
    { id: 2,  type: '男性' },
    { id: 3,  type: '女性' },
    { id: 4,  type: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend ActiveHash::Associations::ActiveRecordExtensions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true 
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze}, allow_blank: true  
  validates :age,  numericality: { greater_than_or_equal_to: 16, less_than_or_equal_to: 120 }, allow_blank: true  


  has_many :collections
  has_many :comments
  has_many :donations
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  belongs_to :gender

  def followed_by?(user)
    follower =  passive_relationships.find_by(following_id: user.id)
    return follower.present?
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @collections = Collection.all
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)
    if @collection.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @collection = Collection.find(params[:id])
    @comments = @collection.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @collection.update(collection_params)
      redirect_to collection_path(@collection)
    else
      render :edit
    end
  end

  def destroy
    @collection.destroy
    redirect_to root_path
  end

  private

  def collection_params
    params.require(:collection).permit(:title, :point, :content, :category_id, {images: []}).merge(user_id: current_user.id)
  end

  def set_collection
    @collection = Collection.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @collection.user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @collection = Collection.find(params[:collection_id]) 
    if @comment.save
      CommentChannel.broadcast_to @collection, { comment: @comment, user: @comment.user }
    end
  end

  def destroy 
    @collection = Collection.find(params[:collection_id])
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    redirect_to collection_path(@collection)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, collection_id: params[:collection_id])
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user,   only: [:new, :create]

  def show
    @donations = Donation.all
  end
  
  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)
    if @donation.valid?
      pay_item
      @donation.save
    else
      render 'new'
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def donation_params
    params.require(:donation).permit(:price, :text).merge(donationd: @user, user_id: current_user.id, token: params[:token])
  end

  def pay_item
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] # 自身のPAY.JPテスト秘密鍵を記述しましょう
    Payjp::Charge.create(
      amount: donation_params[:price],  # 商品の値段
      card: donation_params[:token],    # カードトークン
      currency: 'jpy'                 # 通貨の種類（日本円）
    )
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user,   only: [:show, :edit, :update]

  def show
    @donations = Donation.all
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  private
    def set_user
      @user = User.find(current_user.id)
    end

    def user_params
      params.require(:user).permit(:email, :nickname, :age, :gender_id, :introduction)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/collections/edit.html.erb
<%= render "shared/second-header"%>
<div class="main">
  <div class="collections-sell-contents">
    <div class="collections-sell-main">
      <h2 class="collections-sell-title">創作物情報を編集</h2>
      <%= form_with model: @collection, id: 'new-collection', local: true do |f| %>

      <%= render 'shared/error_messages', model: @collection %>
        
      <%# 作品画像 %>
      <div class="collection-field">
        <div class="weight-bold-text">
          作品画像
          <span class="indispensable">必須</span>
        </div>
        <div id="previews"></div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :images, name: 'collection[images][]', data: {index: 0} %>
        </div>
      </div>
      <%# /作品画像 %>

      <%# 作品の詳細 %>
      <div class="new-collections">
        <div class="weight-bold-text">
          作品名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :title, class:"collections-title", id:"collection-name", placeholder:"作品名（30文字まで)", maxlength:"30" %>
        <div class="collections-explain">
          <div class="weight-bold-text">
            作品のポイント
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :point, class:"collections-point", id:"collection-info", placeholder:"一押しポイント（25文字まで）" ,rows:"1" ,maxlength:"25" %>
          <div class="weight-bold-text">
            作品の説明
          </div>
          <%= f.text_area :content, class:"collections-text", id:"collection-info", placeholder:"作品の魅力や工夫した箇所（1,000文字まで）", maxlength:"1000" %>
        </div>
      </div>
      <div class="collection-detail">
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
        </div>
      <%# /作品の詳細 %>

      <%# 注意ボタン %>
        <div class="caution">
          <p class="sentence">
            <a href="#">禁止されている投稿、</a>
            <a href="#">行為</a>
              を必ずご確認ください。
          </p>
        </div>
      <%# /注意ボタン %>

      <%# 下部ボタン %>
        <div class="sell-btn-contents">
          <%= f.submit "変更する" , class:"sell-btn" %>
          <%=link_to 'もどる', collection_path, class:"back-btn" %>
        </div>
      <%# /下部ボタン %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/collections/index.html.erb
<%= render 'shared/header' %>
  <div class="main">
  <%# トップヘッダー %>
  <% if user_signed_in? %>
    <div class='title-contents'>
      <h2 class='service-title'>
        ようこそ!<br>クリ<span>コレへ!</span>
      </h2>
      <p class='service-explain'>
        クリコレはだれでもかんたんに作品を投稿
      </p>
      <p class='service-explain'>
        アカウントを登録して創作物を投稿しよう!
      </p>
    </div>
    <% if current_user.collections == [] %>
      <div class="welcome-create">
        <p>さあ！自分の作品を登録しよう！</p>
        <%= link_to "投稿する!", new_collection_path, class: 'welcome-create-btn'%>
      </div>
    <% end %> 
    <%= link_to(new_collection_path, class: 'purchase-btn') do %>
      <span class='purchase-btn-text'>作ったものを<br>投稿する</span>
    <% end %> 
  <% else %>
    <div class='title-contents'>
      <h2 class='service-title'>
        ようこそ!<br>クリ<span>コレへ!</span>
      </h2>
      <p class='service-explain'>
        クリコレはだれでもかんたんに作品を投稿
      </p>
      <p class='service-explain'>
        アカウントを登録して創作物を投稿しよう!
      </p>
      <%= link_to "新規登録はこちら!", new_user_registration_path, class: 'welcome-new-user-btn' %>
    </div>
  <% end %>
  <%# /トップヘッダー %>

  <%# お知らせ %>
  <h1 class="notification">お知らせ</h1>
  <div class="announcement-notice">
    <ul class="announcement-notice_list">
      <li class="announcement-notice__item">
        <div class="announcement-notice__item__date">2023/02/27</div>
        <%= link_to "#", class: "announcement-notice__item__link" do %>このアプリについて<% end %>
      </li>
      <li class="announcement-notice__item">
        <div class="announcement-notice__item__date">2023/02/27</div>
        <%= link_to "#", class: "announcement-notice__item__link" do %>寄付機能について<% end %>
      </li>
      <li class="announcement-notice__item">
        <div class="announcement-notice__item__date">2023/02/26</div>
        <%= link_to "#", class: "announcement-notice__item__link" do %>作品投稿の注意<% end %>
      </li>
      <li class="announcement-notice__item">
        <div class="announcement-notice__item__date">2023/02/26</div>
        <%= link_to "#", class: "announcement-notice__item__link" do %>サービス開始のお知らせ<% end %>
      </li>
    </ul>
  </div>
  <%# /お知らせ %>
  
  <%# 作品一覧 %>
  <div class='collection-contents'>
    <h2 class='title'>新規投稿作品</h2>
    <div class="subtitle" >
    </div>
    <ul class='collection-lists'>
      <% @collections.each do |collection| %>
        <li class='collection'>
          <%= link_to collection_path(collection.id) do %>
          <div class='collectionimg-content'>
            <%= image_tag collection.images[0], class: "collection-img" if collection.images.attached? %>
          </div>
          <div class='collection-info'>
            <h3 class='collection-title'>
              <% if collection.title.length >= 12 %>
                <%= collection.title.slice(0, 12)...  %>
              <% else %>
                <%= collection.title %>
              <% end %>
            </h3>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'><%= Favorite.count_by_collection(collection.id) %></span>
              </div>
            <div class="collection-user">
            <% if  current_user == collection.user %>
              <%= link_to  profile_path(@user), class: "collection-nickname" do %>
                <%= collection.user.nickname %>
              <% end %>
            <% else %>
              <%= link_to user_path(collection.user), class: "collection-nickname" do %>
                <%= collection.user.nickname %>
              <% end %>
            <% end %>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <%# /作品一覧 %>
</div>

app/views/collections/new.html.erb
<%= render "shared/second-header"%>
<div class="main">
  <div class="collections-sell-contents">
    <div class="collections-sell-main">
      <h2 class="collections-sell-title">作品情報を入力</h2>
      <%= form_with model: @collection, url: collections_path, id: 'new-collection', local: true do |f| %>

      <%= render 'shared/error_messages', model: @collection %>
        
      <%# 作品画像 %>
      <div class="collection-field">
        <div class="weight-bold-text">
          作品画像
          <span class="indispensable">必須</span>
        </div>
        <div id="previews"></div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード(最大5枚まで)
          </p>
          <%= f.file_field :images, class:'image-btn', name: 'collection[images][]', data: {index: 0} %>
        </div>
      </div>
      <%# /作品画像 %>
      
      <%# 作品説明 %>
      <div class="new-collections">
        <div class="weight-bold-text">
          作品名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :title, class:"collections-title", id:"collection-name", placeholder:"作品名（30文字まで)", maxlength:"30" %>
        <div class="collections-explain">
          <div class="weight-bold-text">
            作品のポイント
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :point, class:"collections-point", id:"collection-info", placeholder:"一押しポイント（25文字まで）" ,rows:"1" ,maxlength:"25" %>
          <div class="weight-bold-text">
            作品の説明
          </div>
          <%= f.text_area :content, class:"collections-text", id:"collection-info", placeholder:"作品の魅力や工夫した箇所（1,000文字まで）", maxlength:"1000" %>
        </div>
      </div>
      <div class="collection-detail">
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
        </div>
      <%# /作品説明 %>

      <%# 注意ボタン %>
        <div class="caution">
          <p class="sentence">
            <a href="#">禁止されている投稿、</a>
            <a href="#">行為</a>
              を必ずご確認ください。
          </p>
        </div>
      <%# /注意ボタン %>

      <%# 下部ボタン %>
        <div class="sell-btn-contents">
          <%= f.submit "投稿する" ,class:"sell-btn" %>
          <%=link_to 'もどる', root_path, class:"back-btn" %>
        </div>
      <%# /下部ボタン %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/collections/show.html.erb
<%= render 'shared/header' %>
<div class="main">
  <%# 作品の概要 %>
  <div class="show-view">
    <div class="show-upper-var">
      <div class="show-title">
        collection-info
      </div>
      <% if user_signed_in? %>
        <% if current_user == @collection.user %>
          <div class="collection-edit-btn">
            <button type="button" class="edit-btn" id="edit-lists">
                <span data-component="text">編集</span>
            </button>
            <ul class="show-edit-lists hidden" id="show-edit-list">
              <li class="edit-list"><%= link_to "編集", edit_collection_path, method: :get, class: "edit-action-btn" %></li>
              <li class="edit-list"><%= link_to "削除", collection_path, method: :delete, class: "delete-action-btn" %></li>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="collection-box">
      <div class="left-content">
        <h2 class="title">
          <%= @collection.title %>
        </h2>
        <% if @collection.images.attached? %>
            <%= image_tag @collection.images.first.variant(resize_to_limit: [400, 400]), class: 'main-image' %>
          <div class="other-images">
            <% @collection.images[0..-1].each do |image| %>
              <div class="other-image">
                <%= image_tag image.variant(resize_to_limit: [400, 400]), width: 400, height: 400 %>
              </div>
           <% end %>
          </div>
        <% end %>
        <div class="favorite-count">
          <span>お気に入り<%= Favorite.count_by_collection(@collection.id) %></span>
        </div>
      </div>
      <div class="right-content">
        <div class="collection-explain-box">
          <span>こだわりポイント!</span>
          <div class="collection-point"><%= @collection.point %></div>
        </div>
        <div class="detail-table">
          <div class="detail-collection"><span>詳細説明</span><br>
            <%= @collection.content %>
          </div>
          <div class="detail-collection"><span>出品者</span>
            <% if  current_user == @collection.user %>
              <%= link_to  profile_path(@user), class: "collection-nickname" do %>
                <%= @collection.user.nickname %>
              <% end %>
            <% else %>
              <%= link_to user_path(@collection.user), class: "collection-nickname" do %>
                <%= @collection.user.nickname %>
              <% end %>
            <% end %>
          </div>
          <div class="detail-collection">カテゴリー
            <%= @collection.category.name %>
          </div>
        </div>
      </div>
    </div>

    <% if user_signed_in? %>
      <% if current_user != @collection.user %>
        <div class="option">
          <div class="favorite-btn">
            <% if current_user.favorite_find(@collection) %>
              <%= link_to 'お気に入りからはずす', collection_favorites_path(@collection), method: :delete %>
            <% else %>
              <%= link_to 'お気に入り登録する', collection_favorites_path(@collection), method: :post %>
            <% end %>
          </div>
          <div class="report-btn">
            <%= link_to "不適切な商品の通報", '#' %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%# /作品の概要 %>

  <%# コメントリスト %>  
    <div class="comments" id="comments">
      <h2 class="comment-list">みんなのコメント</h2>
      <% if @collection.comments == [] %>
        <div class="comment-nil">
            コメントはありません
        </div>
      <% else %>
        <% @collection.comments.each do |comment| %>
          <div class="comment">
            <div class="user-info">
              <%= link_to user_path(comment.user), class: "comment-nickname" do %>
                <%= comment.user.nickname %>
              <% end %>
            </div>
            <div class="comment-content">
              <div class="comment-text">
                <p><%= comment.text%></p>
              </div>
              <% if user_signed_in? %>
                <% if current_user.id == comment.user_id %>
                  <%= link_to "削除", collection_comment_path(@collection, comment), method: :delete, class: "comment-delete-btn", id: "comment-delete" %>
                <% elsif current_user.id == @collection.user_id %>
                  <%= link_to "削除", collection_comment_path(@collection, comment), method: :delete, class: "comment-delete-btn", id: "comment-delete" %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      <%end%>
    </div>
  <%# /コメントリスト %>

  <%# コメントフォーム %>
    <div class="comment-form">
      <div class="comment-box">
        <% if user_signed_in? %>
          <%= form_with model: [@collection, @comment], id: "comment-form" do |f| %>
            <%= f.text_area :text , class: "comment-text-form", placeholder:"ここにコメントを入力"%>
            <p class="comment-warn">
              相手のことを考え丁寧なコメントを心がけましょう。
              <br>
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            </p>
            <%= f.submit "コメントをする", class: "comment-btn" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <%# /コメントフォーム %>
</div>