config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'collections#index'
  resources :collections do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:show, :create, :destroy]
  end
  resources :users, only: :show do
    resources :donations, only: [:new, :create, :show]
    resource :relationships, only: [:show, :create, :destroy]
    get :favorites, on: :collection
  end
  resource :profile, only: [:show, :edit, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '自然' },
    { id: 3, name: '絵画' },
    { id: 4, name: 'インテリア' },
    { id: 5, name: '小物' },
    { id: 6, name: '本' },
    { id: 7, name: '音楽' },
    { id: 8, name: 'ゲーム' },
    { id: 9, name: 'おもちゃ' },
    { id: 10, name: 'グッズ' },
    { id: 11, name: 'プラモデル' },
    { id: 12, name: 'フィギュア' },
    { id: 13, name: 'ハンドメイド' },
    { id: 14, name: 'その他' }
  ]


  include ActiveHash::Associations
  has_many :collections


  end

app/models/collection.rb
class Collection < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :favorites, dependent: :destroy 
  has_many_attached :images

  with_options presence: true do
    validates :title
    validates :point
    validates :category_id,           numericality: { other_than: 1 , message: "を選択してください"}
  end
  validates :images, presence: true 
  validates :images, length: { minimum: 1, maximum: 5, message: "は1枚以上5枚以下にしてください" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :collection

  validates :text, presence: true
end

app/models/donation.rb
class Donation < ApplicationRecord
  attr_accessor :token
  validates :price, presence: true
  validates :text,  presence: true
  validates :token, presence: true

  belongs_to :user
  belongs_to :donationd, class_name: "User", foreign_key: "donationd_id"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user   
  belongs_to :collection   

  validates_uniqueness_of :collection_id, scope: :user_id
  
  def self.count_by_collection(collection_id)
    where(collection_id: collection_id).count
  end

end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1,  type: '---' },
    { id: 2,  type: '男性' },
    { id: 3,  type: '女性' },
    { id: 4,  type: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend ActiveHash::Associations::ActiveRecordExtensions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true 
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze}, allow_blank: true  
  validates :age,  numericality: { greater_than_or_equal_to: 16, less_than_or_equal_to: 120 }, allow_blank: true  


  has_many :collections
  has_many :comments
  has_many :donations
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  belongs_to :gender

  def followed_by?(user)
    follower =  passive_relationships.find_by(following_id: user.id)
    return follower.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?




  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @collection = Collection.find(params[:collection_id]) 
    if @comment.save
      CommentChannel.broadcast_to @collection, { comment: @comment, user: @comment.user }
    end
  end

  def destroy 
    @collection = Collection.find(params[:collection_id])
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    redirect_to collection_path(@collection)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, collection_id: params[:collection_id])
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user,   only: [:new, :create]

  def show
    @donations = Donation.all
  end
  
  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)
    if @donation.valid?
      pay_item
      @donation.save
    else
      render 'new'
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def donation_params
    params.require(:donation).permit(:price, :text).merge(donationd: @user, user_id: current_user.id, token: params[:token])
  end

  def pay_item
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] # 自身のPAY.JPテスト秘密鍵を記述しましょう
    Payjp::Charge.create(
      amount: donation_params[:price],  # 商品の値段
      card: donation_params[:token],    # カードトークン
      currency: 'jpy'                 # 通貨の種類（日本円）
    )
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_collection, only: [:create, :destroy]

  def show 
  end

  def create
    Favorite.create(user_id: current_user.id, collection_id: params[:collection_id])
    redirect_to collection_path(@collection)
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, collection_id: params[:collection_id])
    favorite.destroy
    redirect_to collection_path(@collection)
  end

private

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user,   only: [:show, :edit, :update]

  def show
    @donations = Donation.all
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  private
    def set_user
      @user = User.find(current_user.id)
    end

    def user_params
      params.require(:user).permit(:email, :nickname, :age, :gender_id, :introduction)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_collection-show.html.erb
<div class="user-collection-show">
  <h2><span><%= "#{@user.nickname}"%></span>さんの作品</h2>
  <div class='user-collection-lists'>
    <% @user.collections.each do |collection| %>
      <div class="user-collections">
        <div class="user-collections-left">
          <%= link_to collection_path(collection.id) do %>
            <%= image_tag collection.images[0], class: "user-collection-img" if collection.images.attached? %>
          <% end %>
          <div class='user-collection-info'>
            <%= link_to collection_path(collection.id), class: "user-collection-title" do %>
              <%= collection.title %>
            <% end %>
          </div>
        </div>
        <div class='user-collections-right'>
          <%= image_tag "star.png", class:"user-star-icon" %>
          <span class='user-star-count'><%= Favorite.count_by_collection(collection.id) %></span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_favorite.html.erb
<div class="user-collection-show">
  <h2><span><%= "#{@user.nickname}"%></span>さんのお気に入りした作品</h2>
  <div class='user-collection-lists'>
    <% @user.favorites.each do |favorite| %>
      <div class="user-collections">
        <div class="user-collections-left">
          <%= link_to collection_path(favorite.collection_id) do %>
            <%= image_tag favorite.collection.images[0], class: "user-collection-img" if favorite.collection.images.attached? %>
          <% end %>
          <div class='user-collection-info'>
            <%= link_to collection_path(favorite.collection_id), class: "user-collection-title" do %>
              <%= favorite.collection.title %>
            <% end %>
          </div>
        </div>
        <div class='user-collections-right'>
          <%= image_tag "star.png", class:"user-star-icon" %>
          <span class='user-star-count'><%= Favorite.count_by_collection(favorite.collection.id) %></span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_profile.html.erb
<div class="profile-view">
  <div class="profile-content">
    <span><%= "#{@user.nickname}"%></span>さんのプロフィール
    <table class="table">
      <tbody>
        <tr>
          <th class="table__col1">ユーザー名</th>
          <td class="table__col2"><%= @user.nickname %></td>
        </tr>
        <tr>
          <th class="table__col1">年齢</th>
          <% if @user.age == nil %>
            <td class="table__col2">情報がありません</td>
          <% else %>
            <td class="table__col2"><%= @user.age %>歳</td>
          <% end %>
        </tr>
        <tr>
          <th class="table__col1">性別</th>
          <% if @user.gender_id == nil %>
            <td class="table__col2">情報がありません</td>
          <% elsif @user.gender_id == 1 %>
            <td class="table__col2">情報がありません</td>
          <% else %>
            <td class="table__col2"><%= @user.gender.type %></td>
          <% end %>
        </tr>
        <tr>
          <th class="table__col3">自己紹介</th>
          <% if @user.introduction == nil %>
            <td class="table__col4-nil">情報がありません</td>
          <% elsif @user.introduction == '' %>
            <td class="table__col4-nil">情報がありません</td>
          <% else %>
            <td class="table__col4"><%= @user.introduction %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<% if current_user != @user %>
  <div class="donation">
    <div class="donation-img"></div>
    <div class="donation-inner">
      <div class="donation-link-text">
        <span><%= @user.nickname %></span>さん<br>を支援して応援をしよう！
      </div>
      <div class="donation-link">
        <%= link_to "応援する！", new_user_donation_path(@user), class: 'donation-link-btn' %>
      </div>
    </div>
  </div>
<% end%>

app/views/users/show.html.erb
<%= render 'shared/header' %>
<div class="main">
  <div class="user-show-page">
    <div class="user__wrapper">
      <div class="page-heading">
        <div class="user-show-name">
          <%= "#{@user.nickname}"%><span>さんの情報</span>
        </div>
        <div class="follow">
          <% if @user.followed_by?(current_user) %>
            <%=link_to "フォロー外す", user_relationships_path(@user.id),class: "follow-btn" , method: :delete %>
          <% else %>
            <%=link_to "フォローする", user_relationships_path(@user.id),class: "follow-btn" ,method: :post %>
          <% end %>
        </div>
      </div>
      <!--タブ部分-->
      <ul class="tab-list list-unstyled">
        <li class="tab tab-active">
          ユーザー情報
        </li>
        <li class="tab">
          投稿作品
        </li>
        <li class="tab">
          お気に入りした作品
        </li>
      </ul>
      <!--タブで選択された要素部分-->
      <div class="tabbox-contents">
        <div class="tabbox box-show">
          <%= render 'users/profile' %>    
        </div>
        <div class="tabbox">
          <%= render 'users/collection-show' %>
        </div>
        <div class="tabbox">
          <%= render 'users/favorite' %>
        </div>
      </div>
    </div>
  </div>
</div>