config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'collections#index'
  resources :collections do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:show, :create, :destroy]
  end
  resources :users, only: :show do
    resources :donations, only: [:new, :create, :show]
    resource :relationships, only: [:show, :create, :destroy]
    get :favorites, on: :collection
  end
  resource :profile, only: [:show, :edit, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '自然' },
    { id: 3, name: '絵画' },
    { id: 4, name: 'インテリア' },
    { id: 5, name: '小物' },
    { id: 6, name: '本' },
    { id: 7, name: '音楽' },
    { id: 8, name: 'ゲーム' },
    { id: 9, name: 'おもちゃ' },
    { id: 10, name: 'グッズ' },
    { id: 11, name: 'プラモデル' },
    { id: 12, name: 'フィギュア' },
    { id: 13, name: 'ハンドメイド' },
    { id: 14, name: 'その他' }
  ]


  include ActiveHash::Associations
  has_many :collections


  end

app/models/collection.rb
class Collection < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :favorites, dependent: :destroy 
  has_many_attached :images

  with_options presence: true do
    validates :title
    validates :point
    validates :category_id,           numericality: { other_than: 1 , message: "を選択してください"}
  end
  validates :images, presence: true 
  validates :images, length: { minimum: 1, maximum: 5, message: "は1枚以上5枚以下にしてください" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :collection

  validates :text, presence: true
end

app/models/donation.rb
class Donation < ApplicationRecord
  attr_accessor :token
  validates :price, presence: true
  validates :text,  presence: true
  validates :token, presence: true

  belongs_to :user
  belongs_to :donationd, class_name: "User", foreign_key: "donationd_id"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user   
  belongs_to :collection   

  validates_uniqueness_of :collection_id, scope: :user_id
  
  def self.count_by_collection(collection_id)
    where(collection_id: collection_id).count
  end

end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1,  type: '---' },
    { id: 2,  type: '男性' },
    { id: 3,  type: '女性' },
    { id: 4,  type: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend ActiveHash::Associations::ActiveRecordExtensions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true 
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze}, allow_blank: true  
  validates :age,  numericality: { greater_than_or_equal_to: 16, less_than_or_equal_to: 120 }, allow_blank: true  


  has_many :collections
  has_many :comments
  has_many :donations
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  belongs_to :gender

  def followed_by?(user)
    follower =  passive_relationships.find_by(following_id: user.id)
    return follower.present?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @collection = Collection.find(params[:collection_id]) 
    if @comment.save
      CommentChannel.broadcast_to @collection, { comment: @comment, user: @comment.user }
    end
  end

  def destroy 
    @collection = Collection.find(params[:collection_id])
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    redirect_to collection_path(@collection)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, collection_id: params[:collection_id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>クリコレ！</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script type="text/javascript" src="https://js.pay.jp/v2/pay.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all'  %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="inner">
    <div class="upper-nav">
      <div class="header-left">
        <%= link_to root_path, class: :app_title do %>
          クリ<span class="kore">コレ！</span>
        <% end %>
      </div>
      <div class="header-right">
        <% if user_signed_in? %>
          <div class="nav__right">
            <div class="user_nickname" id="lists"><%= current_user.nickname %></div>
              <ul class="user-menu-wrapper hidden" id="user-menu-list">
                <li class="user-menu-list"><%= link_to "マイページ", profile_path(@user), class: :menu_list_btn %></li>
                <li class="user-menu-list"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :menu_list_btn  %></li>
                <li class="user-menu-list"><%= link_to "フォロー管理", user_relationships_path(current_user.id), class: :menu_list_btn  %></li>
              </ul>
          </div>
        <% else %>
          <div class="nav__right">
            <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
            <%= link_to "アカウント登録", new_user_registration_path, class: :nav__btn %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="under-nav">
    <ul class="global__list">
      <li class="list__inner">
        <a class="inner__item" href="/">
          <span class="item__text">トップ</span>
        </a>
      </li>
      <li class="list__inner">
        <a class="inner__item" href="#">
          <span class="item__text">クリコレとは</span>
        </a>
      </li>
      <li class="list__inner">
        <a class="inner__item" href="#">
          <span class="item__text">カテゴリー</span>
        </a>
      </li>
      <li class="list__inner">
        <a class="inner__item" href="#">
          <span class="item__text">ランキング</span>
        </a>
      </li>
    </ul>
  </div>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/shared/_second-header.html.erb
<header>
  <div class="inner">
    <div class="upper-nav">
      <div class="header-left">
        <%= link_to root_path, class: :app_title do %>
          クリ<span class="kore">コレ！</span>
        <% end %>
      </div><div class="header-right">
        <% if user_signed_in? %>
          <div class="nav__right">
            <div class="user_nickname" id="lists"><%= current_user.nickname %></div>
              <ul class="user-menu-wrapper hidden" id="user-menu-list">
                <li class="user-menu-list"><%= link_to "マイページ", profile_path(@user), class: :my_page_link %></li>
                <li class="user-menu-list"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %></li>
              </ul>
          </div>
        <% else %>
          <div class="nav__right">
            <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
            <%= link_to "アカウント登録", new_user_registration_path, class: :nav__btn %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="under-nav">
  </div>
</header>