config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'collections#index'
  resources :collections do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:show, :create, :destroy]
  end
  resources :users, only: :show do
    resources :donations, only: [:new, :create, :show]
    resource :relationships, only: [:show, :create, :destroy]
    get :favorites, on: :collection
  end
  resource :profile, only: [:show, :edit, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '自然' },
    { id: 3, name: '絵画' },
    { id: 4, name: 'インテリア' },
    { id: 5, name: '小物' },
    { id: 6, name: '本' },
    { id: 7, name: '音楽' },
    { id: 8, name: 'ゲーム' },
    { id: 9, name: 'おもちゃ' },
    { id: 10, name: 'グッズ' },
    { id: 11, name: 'プラモデル' },
    { id: 12, name: 'フィギュア' },
    { id: 13, name: 'ハンドメイド' },
    { id: 14, name: 'その他' }
  ]


  include ActiveHash::Associations
  has_many :collections


  end

app/models/collection.rb
class Collection < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :favorites, dependent: :destroy 
  has_many_attached :images

  with_options presence: true do
    validates :title
    validates :point
    validates :category_id,           numericality: { other_than: 1 , message: "を選択してください"}
  end
  validates :images, presence: true 
  validates :images, length: { minimum: 1, maximum: 5, message: "は1枚以上5枚以下にしてください" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :collection

  validates :text, presence: true
end

app/models/donation.rb
class Donation < ApplicationRecord
  attr_accessor :token
  validates :price, presence: true
  validates :text,  presence: true
  validates :token, presence: true

  belongs_to :user
  belongs_to :donationd, class_name: "User", foreign_key: "donationd_id"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user   
  belongs_to :collection   

  validates_uniqueness_of :collection_id, scope: :user_id
  
  def self.count_by_collection(collection_id)
    where(collection_id: collection_id).count
  end

end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1,  type: '---' },
    { id: 2,  type: '男性' },
    { id: 3,  type: '女性' },
    { id: 4,  type: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend ActiveHash::Associations::ActiveRecordExtensions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true 
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze}, allow_blank: true  
  validates :age,  numericality: { greater_than_or_equal_to: 16, less_than_or_equal_to: 120 }, allow_blank: true  


  has_many :collections
  has_many :comments
  has_many :donations
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  belongs_to :gender

  def followed_by?(user)
    follower =  passive_relationships.find_by(following_id: user.id)
    return follower.present?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @collection = Collection.find(params[:collection_id]) 
    if @comment.save
      CommentChannel.broadcast_to @collection, { comment: @comment, user: @comment.user }
    end
  end

  def destroy 
    @collection = Collection.find(params[:collection_id])
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    redirect_to collection_path(@collection)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, collection_id: params[:collection_id])
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user,   only: [:new, :create]

  def show
    @donations = Donation.all
  end
  
  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)
    if @donation.valid?
      pay_item
      @donation.save
    else
      render 'new'
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def donation_params
    params.require(:donation).permit(:price, :text).merge(donationd: @user, user_id: current_user.id, token: params[:token])
  end

  def pay_item
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] # 自身のPAY.JPテスト秘密鍵を記述しましょう
    Payjp::Charge.create(
      amount: donation_params[:price],  # 商品の値段
      card: donation_params[:token],    # カードトークン
      currency: 'jpy'                 # 通貨の種類（日本円）
    )
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_collection, only: [:create, :destroy]

  def show 
  end

  def create
    Favorite.create(user_id: current_user.id, collection_id: params[:collection_id])
    redirect_to collection_path(@collection)
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, collection_id: params[:collection_id])
    favorite.destroy
    redirect_to collection_path(@collection)
  end

private

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user,   only: [:show, :edit, :update]

  def show
    @donations = Donation.all
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  private
    def set_user
      @user = User.find(current_user.id)
    end

    def user_params
      params.require(:user).permit(:email, :nickname, :age, :gender_id, :introduction)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/donations/create.html.erb
<div class="main">
<%= render 'shared/header' %>
  <div class="contents-row">
    <div class="success">
      <div class="success-text">
        <h1>THANK YOU!!</h1>
        <p>応援メッセージを送信しました。</p>
        <a class="create-back-btn" href="/">トップページへ</a>
      </div>
    </div>
  </div>
</div>

app/views/donations/new.html.erb
<%= render "shared/second-header"%>
<div class="main">
  <div class="donation-header">
    <div class="donation-header-text">
        <span><%= @user.nickname %></span>さん<br>を支援して応援をしよう！
    </div>
  </div>
  <%= form_with  model: @donation, url: user_donations_path,id: 'charge-form', class: 'registration-main',local: true do |f| %>
  <%= render 'shared/error_messages', model: @donation %>
  <div class='donation-form-wrap'>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="weight-bold-text">応援メッセージ</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :text, class:"support-message", placeholder:"例)いつも応援してます！" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="weight-bold-text">金額</label>
        <span class="indispensable">必須</span>
      </div>
      <div class="price-form">
        <%= f.text_field :price, class:"price", placeholder:"例)2000" %>円
      </div>
      <div class="price-caution">
        <p>※クレジットカードでの応援のみとなります。</p>
      </div>
    </div>

    <div class="card-form">
      <div class="card-top">クレジットカード情報</div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード番号</label>
        </div>
        <div id="number-form" class="input-default"></div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">期限</label>
        </div>
        <div id="expiry-form" class="input-default"></div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード背面4桁もしくは3桁の番号</label>
        </div>
        <div id="cvc-form" class="input-default"></div>
      </div>
    </div>
      <div class="donation-btns">
        <%= f.submit "応援メッセージを送る!", class:"donation-btn", id: "button" %>
        <%=link_to 'もどる', root_path, class:"donation-back-btn" %>
      </div>
  </div>
  <% end %>
</div>